# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false

addons:
 apt:
   update: true
   sources:
     - sourceline: 'ppa:opencpu/imagemagick'
   packages:
     - libmagick++-dev

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

notifications:
  email:
    on_success: change
    on_failure: change
